const LoanRequest = require('../models/LoanRequest');
const Lender = require('../models/Lender');

/**
 * POST /api/public/loan-request
 * Guest submits a loan request — no authentication required.
 */
const createPublicLoanRequest = async (req, res) => {
    try {
        const { lenderId, guestName, guestPhone, guestEmail, amount, purpose, message } = req.body;

        if (!lenderId || !guestName || !guestPhone || !amount || !purpose) {
            return res.status(400).json({
                success: false,
                message: 'lenderId, name, phone, amount and purpose are required',
            });
        }

        // Validate lender exists and is public
        const lender = await Lender.findById(lenderId).select('businessName ownerName isPublic');
        if (!lender) {
            return res.status(404).json({ success: false, message: 'Lender not found' });
        }

        // Check for duplicate pending request from same phone to same lender
        const existing = await LoanRequest.findOne({
            lenderId,
            guestPhone,
            status: 'pending',
        });
        if (existing) {
            return res.status(409).json({
                success: false,
                message: 'You already have a pending request with this lender. Check your request status first.',
            });
        }

        const loanRequest = await LoanRequest.create({
            lenderId,
            guestName: guestName.trim(),
            guestPhone: guestPhone.trim(),
            guestEmail: guestEmail?.trim() || undefined,
            amount: Number(amount),
            purpose,
            message: message?.trim() || undefined,
            // trackingToken is auto-generated by model pre-save hook
        });

        // Notify lender via Socket.IO (if connected)
        const io = req.app.get('io');
        if (io) {
            const userSocketMap = req.app.get('userSocketMap');
            const lenderSocketId = userSocketMap?.get(lenderId.toString());
            if (lenderSocketId) {
                io.to(lenderSocketId).emit('new_loan_request', {
                    requestId: loanRequest._id,
                    guestName: loanRequest.guestName,
                    amount: loanRequest.amount,
                    purpose: loanRequest.purpose,
                });
            }
        }

        return res.status(201).json({
            success: true,
            message: 'Loan request submitted successfully!',
            data: {
                requestId: loanRequest._id,
                trackingToken: loanRequest.trackingToken,
                lenderName: lender.businessName,
                // Tell the customer to save their phone as tracking ID
                trackingPhone: loanRequest.guestPhone,
            },
        });
    } catch (err) {
        console.error('createPublicLoanRequest error:', err);
        return res.status(500).json({ success: false, message: 'Server error' });
    }
};

/**
 * GET /api/public/loan-request/track?phone=XXXXXXXXXX
 * Guest checks their request status by phone number — no auth required.
 */
const trackLoanRequest = async (req, res) => {
    try {
        const { phone } = req.query;

        if (!phone) {
            return res.status(400).json({ success: false, message: 'Phone number is required' });
        }

        const requests = await LoanRequest.find({ guestPhone: phone.trim() })
            .populate('lenderId', 'businessName ownerName address interestRate')
            .sort({ createdAt: -1 })
            .lean();

        if (!requests.length) {
            return res.status(404).json({
                success: false,
                message: 'No loan requests found for this phone number.',
            });
        }

        // Strip trackingToken from response UNLESS status is accepted
        const sanitised = requests.map((r) => ({
            _id: r._id,
            lender: r.lenderId,
            amount: r.amount,
            purpose: r.purpose,
            message: r.message,
            status: r.status,
            createdAt: r.createdAt,
            // Only expose trackingToken if accepted (needed for chat)
            trackingToken: r.status === 'accepted' ? r.trackingToken : undefined,
        }));

        return res.json({ success: true, data: sanitised });
    } catch (err) {
        console.error('trackLoanRequest error:', err);
        return res.status(500).json({ success: false, message: 'Server error' });
    }
};

module.exports = { createPublicLoanRequest, trackLoanRequest };
